add base images to core
openproblems-bio/core pull request #5
Opened 2024-08-05 08:48 UTC by KaiWaldrant

2024-08-08 15:05 UTC, rcannood requested changes

2024-08-08 15:05 UTC, rcannood commented on base_images/CHANGELOG.md
> +* Changed container registry from `ghcr.io/openproblems-bio/base_images` to docker hub `openproblems/base_images`. (PR #5")
Fix formatting ^^

2024-08-08 15:05 UTC, rcannood commented on base_images/README.md
> +- [`openproblems/base_images/tensorflow_nvidia:1.0.0`](src/tensorflow_nvidia)
Docker hub doesn't support multiple slashes in the docker image name.

I think we'll need to rename it to `openproblems/base_python:1.0.0` and so on.

2024-08-08 19:09 UTC, KaiWaldrant commented
Close #3

2024-08-09 07:00 UTC, rcannood approved these changes

2024-08-09 07:00 UTC, rcannood commented on base_images/CHANGELOG.md
> +* Change container registry from `ghcr.io/openproblems-bio/base_images` to docker hub `openproblems/base_*`. (PR #5)
* Change container registry from `ghcr.io/openproblems-bio/base_images` to docker hub `openproblems/base_*` (PR #5).

2024-08-09 07:10 UTC, merged